const Products = [
	{
		name: "Τρυπάνι SDS 8 mm",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YD8vXO.webp",
	},
	{
		name: "Τρυπάνι SDS 10 mm",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YD8vXO.webp",
	},
	{
		name: "Τρυπάνι SDS 12 mm",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YD8vXO.webp",
	},
	{
		name: "Τρυπάνι SDS 14 mm",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YD8vXO.webp",
	},
	{
		name: "Τρυπάνι SDS 16 mm",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YD8vXO.webp",
	},
	{
		name: "Τρυπάνι SDS 18 mm",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YD8vXO.webp",
	},
	{
		name: "Τρυπάνι SDS 20 mm",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YD8vXO.webp",
	},
	{
		name: "Τρυπάνι SDS 22 mm",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YD8vXO.webp",
	},
	{
		name: "Τρυπάνι SDS 8 mm τετράκοπο",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YDJ9rC.webp",
	},
	{
		name: "Τρυπάνι SDS 10 mm τετράκοπο",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YDJ9rC.webp",
	},
	{
		name: "Τρυπάνι Μαύρο Αέρος",
		description: "Τρυπάνι ακίδος για ξύλο της Benman. Τρύπημα ακριβείας χάρη στην ακίδα κεντραρίσματος, τις δύο κοπτικές ακμές και την διπλή ελίκωση που διαθέτει. Προσφέρει γρήγορη διάτρηση, χωρίς φθορές στο ξύλο. Κατασκευασμένο σύμφωνα με τα πρότυπα DIN8037. Κατάλληλο για ξύλο, μελαμίνη, και κόντρα-πλακέ.",
		category: "Τρυπάνι Αέρος",
		amount: "",
		image: "https://s6.imgcdn.dev/YDJRme.webp",
	},
	{
		name: "Διαμαντοτρύπανο Benman",
		description: "Κατάλληλο για τοίχους, πέτρα, τούβλα και μπετόν.",
		category: "Διαμαντοτρύπανο",
		amount: "",
		image: "https://s6.imgcdn.dev/YDJt1M.webp",
	},
	{
		name: "Τρυπάνι Γυαλιού",
		description: "Τρυπάνι ειδικό για γυαλί και πλακάκια.",
		category: "Τρυπάνι Γυαλιού",
		amount: "",
		image: "https://s6.imgcdn.dev/YDJWWd.webp",
	},
	{
		name: "Διαμαντοτρύπανο Καρβιδίου",
		description: "Με κυλινδρικό στέλεχος. Κατάλληλο για χρήση με & χωρίς κρούση. Ειδικά σχεδιασμένο καρβίδιο για μεγαλύτερη ταχύτητα, αντοχή στη φθορά και σχεδιασμένο σπιράλ για άριστο τρύπημα. Για γρανίτες, μάρμαρα και πολύ δυνατά υλικά.",
		category: "Διαμαντοτρύπανο",
		amount: "",
		image: "https://s6.imgcdn.dev/YDJLPh.webp",
	},
	{
		name: "Τρυπάνι Ακίδος με Κυλινδρικό Στέλεχος",
		description: "Τρυπάνι ακίδος για ξύλο της Benman. Τρύπημα ακριβείας χάρη στην ακίδα κεντραρίσματος, τις δύο κοπτικές ακμές και την διπλή ελίκωση που διαθέτει. Προσφέρει γρήγορη διάτρηση, χωρίς φθορές στο ξύλο.",
		category: "Τρυπάνι Ακίδος",
		amount: "",
		image: "https://s6.imgcdn.dev/YDJFrO.webp",
	},
	{
		name: "Τρυπάνι Κοβαλτίου",
		description: "",
		category: "Τρυπάνι Κοβαλτίου",
		amount: "",
		image: "https://s6.imgcdn.dev/YDJHqn.webp",
	},
	{
		name: "Benman Ποτηροπρίονο",
		description: "Ποτηροπρίονο της εταιρείας Benman για την ευκολότερη δημιουργία στρογγυλών οπών σε επιφάνειες εργασίας. Είναι κατάλληλο για διάτρηση σε ξύλο και μέταλλο. Από 33 έως 108mm.",
		category: "Ποτηροπρίονο",
		amount: "",
		image: "https://i.imgur.com/yArLwyS.png",
	},
	{
		name: "Τρυπάνι CYL-3",
		description: "Για περιστροφικά δράπανα/δραπανοκατσάβιδα, για κρουστικά δράπανα/δραπανοκατσάβιδα. Υψηλή αντοχή στη φθορά χάρη στο ανθεκτικό μείγμα καρβιδίου, σχεδιασμένο και κατασκευασμένο από τη Bosch. Αποτελεσματική διπλή ελίκωση σε σχήμα U, για καλή απομάκρυνση της σκόνης, μείωση τριβής και μεγάλη διάρκεια ζωής.",
		category: "Ποτηροπρίονο",
		amount: "",
		image: "https://i.imgur.com/U6eAV38.png",
	},
	{
		name: "Maco Ποτηροτρύπανo HSS",
		description: "Της εταιρείας Maco για την ευκολότερη δημιουργία στρογγυλών οπών σε επιφάνειες εργασίας. Είναι από υλικό ενισχυμένου χάλυβα που εξασφαλίζει αντοχή και το καθιστά ανθεκτικό στις υψηλές θερμοκρασίες. Είναι κατάλληλο για διάτρηση σε ξύλο, μέταλλο και πλαστικό.",
		category: "Ποτηροπρίονο",
		amount: "",
		image: "https://i.imgur.com/l7bT1QC.png",
	},
]