const Products = [
	/*=========
	   Benman
	===========*/
	{
		name: "Benman Πλαγιοκόφτης Ηλεκτρολόγου Powergrip Μήκους 145mm",
		description: "Διαθέσιμος σε μήκος των 145mm και 160mm.",
		category: "Πλαγιοκόφτης",
		amount: "",
		image: "https://i.imgur.com/z2wJtmN.png",
	},
	{
		name: "Benman Πένσα Ίσια",
		description: "Διαθέσιμα μήκη: 160mm, 180mm, 200mm.",
		category: "Πένσα",
		amount: "",
		image: "https://i.imgur.com/QngDOTR.png",
	},
	{
		name: "Benman Τανάλια Μήκους 200mm",
		description: "Μαλακό σύρμα 220 Ν/mm²: 4,50mm. Συσκευή νυχιών Ø750 Ν/mm²: 4,00mm. Σκληρό σύρμα Ø1800 Ν/mm²: 3,50mm",
		category: "Τανάλια",
		amount: "",
		image: "https://i.imgur.com/w7MN5Mh.png",
	},
	{
		name: "Μετροταινία BENMAN 71018",
		description: "",
		category: "Μέτρο",
		amount: "",
		image: "https://i.imgur.com/eHsWb6t.png",
	},
	{
		name: "Benman Μυστρί",
		description: "Μυστρί σοβατζήδων λοξό με ξύλινη λαβή και μεταλλική λάμα.",
		category: "Μυστρί",
		amount: "",
		image: "https://i.imgur.com/mlKaXWj.png",
	},
	{
		name: "Benman Ξύστρα Πολλαπλών Χρήσεων 63mm",
		description: "",
		category: "Ξύστρα",
		amount: "",
		image: "https://i.imgur.com/hbivYQa.png",
	},
	{
		name: "Benman Σπάτουλα με Inox Λάμα 140mm",
		description: "Φαρδιά σπάτουλα Inox με ξύλινη λαβή, ιδανική για ελαιοχρωματιστικές εργασίες.",
		category: "Σπάτουλα",
		amount: "",
		image: "https://i.imgur.com/ColQSe5.png",
	},
	{
		name: "Benman Σπάτουλα Στοκαδόρος",
		description: "Σπάτουλα για στοκάρισμα κατασκευασμένη απο υψηλής ποιότητας ατσάλι με ξύλινη λαβή. Για επαγγελματίες και ερασιτέχνες. Διαθέσιμη από 20mm έως 50mm.",
		category: "Σπάτουλα",
		amount: "",
		image: "https://i.imgur.com/dmrnoqr.png",
	},
	{
		name: "Benman Σπάτουλα Ξύστρα",
		description: "Σπάτουλα-ξύστρα από υψηλής ποιότητας μέταλλο Ιαπωνίας και ξύλινη λαβή. Ιδανική για επαγγελματική χρήση. Συνολικό μήκος: 19.5cm. Πλάτος: διαθέσιμη από 60mm έως 80mm.",
		category: "Σπάτουλα",
		amount: "",
		image: "https://i.imgur.com/MiGH8dL.png",
	},
	{
		name: "Benman Σπάτουλα Πλακιδίων",
		description: "",
		category: "Σπάτουλα Πλακιδίων",
		amount: "",
		image: "https://i.imgur.com/mEOQU1g.png",
	},
	{
		name: "Benman - Σπάτουλα με Μακριά Λάμα 120mm",
		description: "",
		category: "Σπάτουλα Πλακιδίων",
		amount: "",
		image: "https://i.imgur.com/EXxjSCx.png",
	},
	{
		name: "Δίσκος Κοπής Μετάλλου Benman",
		description: "Διάμετρος: 115 mm & 125 mm",
		category: "Δίσκος Κοπής Μετάλλου",
		amount: "",
		image: "https://s6.imgcdn.dev/JTuxO.webp",
	},
	{
		name: "Benman μαγνητικό αλφάδι LM12",
		description: "Benman μαγνητικό Αλφάδι LΜ με δύο μάτια 40cm. Κατασκευασμένο από ανοξειδωμένο αλουμίνιο πάχους 1,30mm, δεν φθείρεται και δεν σκουριάζει, έχει ενσωματωμένος χάρακας ακριβείας, εξαιρετικής ποιότητας μαγνήτες, με πατενταρισμένα μάτια ακριβείας.",
		category: "Αλφάδι",
		amount: "",
		image: "https://s6.imgcdn.dev/JrDPe.webp",
	},
	{
		name: "Πριόνι κυρτό γενικής χρήσης",
		description: "Πριόνι Κυρτό Γενικής Χρήσης με Διπλό Δόντι Benman, υψηλής αντοχής λεπίδα από ατσάλι ιαπωνίας, ιδανικό για κλαδιά και κορμούς μικρών δέντρων, λαβή από σκληρό ξύλο για μεγαλύτερη αντοχή στο χρόνο. Mέγεθος: 35cm",
		category: "Πριόνι",
		amount: "",
		image: "https://s6.imgcdn.dev/JrY90.webp",
	},
	{
		name: "Πριονάκι Σέγας για Κόντρα Πλακέ",
		description: "115mm Benman Clean Cut.",
		category: "Πριόνι",
		amount: "",
		image: "https://s6.imgcdn.dev/JxbPO.webp",
	},
	{
		name: "Benman Δεματικά Καλωδίων Μαύρα 100 Τεμάχια",
		description: "Διαστάσεις: 100x2.5mm, 140x2.5mm, 200x2.5mm, 140x3.6mm, 200x3.6mm, 250x3.6mm, 300x3.6mm, 370x3.6mm, 200x4.8mm, 250x4.8mm, 300x4.8mm, 370x4.8mm, 200x7.6mm, 250x7.6mm, 300x7.6mm, 370x7.6mm.",
		category: "Δεματικά",
		amount: "",
		image: "https://s6.imgcdn.dev/Jxm8g.webp",
	},
	{
		name: "Benman Δεματικά Καλωδίων Λευκά 100 Τεμάχια",
		description: "Διαστάσεις: 100x2.5mm, 140x2.5mm, 200x2.5mm, 140x3.6mm, 200x3.6mm, 250x3.6mm, 300x3.6mm, 370x3.6mm, 200x4.8mm, 250x4.8mm, 300x4.8mm, 370x4.8mm, 200x7.6mm, 250x7.6mm, 300x7.6mm, 370x7.6mm.",
		category: "Δεματικά",
		amount: "",
		image: "https://s6.imgcdn.dev/JxFkv.webp",
	},
	/*===========
	   FF Group
	=============*/
	{
		name: "Φαλτσέτα FF Group",
		description: "Πλάτος Λάμας: 18mm, περιλαμβάνει 3 λάμες.",
		category: "Φαλτσέτα",
		amount: "",
		image: "https://i.imgur.com/BQlZdoL.png",
	},
	{
		name: "FF Group Λεπίδες Φαλτσέτας 10 τμχ.",
		description: "Σπαστές ανταλλακτικές λάμες 18mm, διαιρούνται σε εφτά κομμάτια με πάχος λάμας 0.55mm.",
		category: "Λάμες Φαλτσέτας",
		amount: "",
		image: "https://i.imgur.com/ay8Xlm0.png",
	},
	{
		name: "FF Group Πένσα Ίσια Ηλεκτρολόγου",
		description: "Πένσα επαγγελματικής χρήσης κατασκευασμένη από ατσάλι χρωμίου-βαναδίου με κοπτικές ακμές μεγάλου μήκους. Οι εργονομικές λαβές της διαθέτουν επένδυση πλαστικού δύο υλικών. Παρέχει προστασία VDE 1000 V και είναι ιδανική για ηλεκτρολόγους. Παρέχεται σε μήκη των 180mm και 200mm.",
		category: "Πένσα",
		amount: "",
		image: "https://i.imgur.com/hZjxuQK.png",
	},
	{
		name: "FF Group Πλαγιοκόφτης Ηλεκτρολόγου 160mm",
		description: "Πλαγιοκόφτης με εργονομική λαβή για άνετη χρήση και νικελομένη κεφαλή για αντοχή στη διάβρωση. Από υψηλής ποιότητας χρωμοβανάδιο, σφυρήλατο, ολικά σκληρυμένο με θερμική επεξεργασία.",
		category: "Πλαγιοκόφτης",
		amount: "",
		image: "https://i.imgur.com/zbguLDy.png",
	},
	{
		name: "FF Group Γαλλικό Κλειδί",
		description: "Το γαλλικό κλειδί της εταιρείας F.F. Group διαθέτει μήκος 300mm και είναι κατάλληλο για χρήση σε μηχανουργικές, υδραυλικές εργασίες και άλλα μαστορέματα. Διαθέτει ανθεκτικό σχεδιασμό και εργονομική λαβή για σύσφιξη ή χαλάρωση βιδών και παξιμαδιών έως 37mm.",
		category: "Γαλλικό Κλειδί",
		amount: "",
		image: "https://i.imgur.com/HPbx8Dg.png",
	},
	{
		name: "Ανταλλακτικές Λάμες FF GROUP",
		description: "Περιλαμβάνει 10 λάμες εξαιρετικά κοφτερές SK5 Blades. Κόβει με ευκολία μοκέτες, χαρτοκιβώτια, πλαστικά κ.α. Πολύ κοφτερές λεπίδες για μεγάλη διάρκεια χρήσης",
		category: "Λάμες Φαλτσέτας",
		amount: "",
		image: "https://i.imgur.com/YWj1L8c.png",
	},
	{
		name: "FF GROUP Μετροταινία",
		description: "Μέτροταινία ρολό με σύστημα power lock, ελαστική επένδυση και λάμα 16 mm, μήκους 3 μέτρων. Διαθέτει κλιπ ζώνης. Είναι με Αυτόματη Επαναφορά και Μαγνήτη 16mm x 3m.",
		category: "Μέτρο",
		amount: "",
		image: "https://i.imgur.com/mnQoh7M.png",
	},
	{
		name: "Συρματόβουρτσα Χειρός FF Group",
		description: "",
		category: "Συρματόβουρτσα",
		amount: "",
		image: "https://i.imgur.com/H2spwO3.png",
	},
	{
		name: "FF Group Συρματόβουρτσα Καμπάνα",
		description: "Για Γωνιακό Τροχό 150mm με Πάσο Μ14.",
		category: "Συρματόβουρτσα",
		amount: "",
		image: "https://i.imgur.com/CmxWKcg.png",
	},
	{
		name: "Δίσκος Κοπής Μετάλλου Inox FF Group",
		description: "Φ125x1.0",
		category: "Δίσκος Κοπής Μετάλλου",
		amount: "",
		image: "https://s6.imgcdn.dev/JT4Hn.webp",
	},
	{
		name: "F.F. Group Μαγνητικό Κατσαβίδι Σταυρός",
		description: "Κατσαβίδι σταυρός της εταιρείας F.F. Group, με μέγεθος μύτης PH0 και μήκος 60 χιλιοστά. Διαθέτει μαγνητική μύτη ώστε να κρατάει τις βίδες πριν την τοποθέτησή τους.",
		category: "Κατσαβίδι",
		amount: "",
		image: "https://s6.imgcdn.dev/JTlIT.webp",
	},
	/*========
	   Bosch
	==========*/
	{
		name: "Σετ λάμες σέγας Bosch",
		description: "Σετ λάμες σέγας Bosch ιδανικές για κοπή σε ξύλο. H συσκευασία περιλαμβάνει 5 τεμάχια.",
		category: "Λάμες",
		amount: "",
		image: "https://s6.imgcdn.dev/JxddK.webp",
	},
	/*========
	   Other
	==========*/
	{
		name: "Φαλτσέτα Tech Boss",
		description: "",
		category: "Φαλτσέτα",
		amount: "",
		image: "https://i.imgur.com/n8769n6.png",
	},
	{
		name: "Vorel Φαλτσέτα 9mm",
		description: "Μεταλλική κατασκευή.",
		category: "Φαλτσέτα",
		amount: "",
		image: "https://i.imgur.com/CUMBJJw.png",
	},
	{
		name: "Φαλτσέτα Luna",
		description: "Οικονομική φαλτσέτα.",
		category: "Φαλτσέτα",
		amount: "",
		image: "https://i.imgur.com/936jGvB.png",
	},
	{
		name: "YATO Φαλτσέτα 25mm",
		description: "Με κουμπί αυτόματου κλειδώματος, αντέχει δύναμη 30 kg.",
		category: "Φαλτσέτα",
		amount: "",
		image: "https://i.imgur.com/BllzANL.png",
	},
	{
		name: "Ανταλλακτικά Φαλτσέτας Tajima",
		description: "10 τεμαχίων.",
		category: "Λάμες Φαλτσέτας",
		amount: "",
		image: "https://i.imgur.com/P5HmAnP.png",
	},
	{
		name: "Μαύρα Ανταλλακτικά Φαλτσέτας Tajima",
		description: "10 τεμαχίων.",
		category: "Λάμες Φαλτσέτας",
		amount: "",
		image: "https://i.imgur.com/fapuSQQ.png",
	},
	{
		name: "Finder Σετ 9 Κλειδιά Torx",
		description: "Σετ κλειδιά τύπου Torx - Standard 9τμχ.",
		category: "Κλειδιά",
		amount: "",
		image: "https://i.imgur.com/y5sQuHo.png",
	},
	{
		name: "Ρυθμιζόμενο Κλειδί Wokin 12\"",
		description: "Μαύρο φινίρισμα. Μέγιστο άνοιγμα 36mm 1,42\"",
		category: "Κλειδιά",
		amount: "",
		image: "https://i.imgur.com/XnC5GnA.png",
	},
	{
		name: "Μέτρο Ρολό Giant Megalock KDS",
		description: "Παραδοσιακό μοντέλο βαρέως τύπου για επαγγελματίες. Το κουμπί on-off, διακόπτης κλειδώματος κλειδώνει την ταινία σε οποιαδήποτε θέση και σε οποιοδήποτε σημείο. Ακρυλική επίστρωση. Ταινία μονής όψης. Άγκιστρο άκρου με 2 πριτσίνια.",
		category: "Μέτρο",
		amount: "",
		image: "https://i.imgur.com/OpELcJd.png",
	},
	{
		name: "L' Outil Parfait Ξύστρα Rigid Κοντή 65mm",
		description: "Ξύστρα με ξύλινη λαβή, εξαιρετικής αντοχής από υψηλής ποιότητας μέταλλο.",
		category: "Ξύστρα",
		amount: "",
		image: "https://i.imgur.com/mBTXk7w.png",
	},
	{
		name: "Yato Ψαλίδι Χάρτου",
		description: "",
		category: "Ψαλίδι",
		amount: "",
		image: "https://i.imgur.com/KdevXVp.png",
	},
	{
		name: "Bellota Ψαλίδι Γενικής Χρήσης Μήκους 180mm",
		description: "",
		category: "Ψαλίδι",
		amount: "",
		image: "https://i.imgur.com/Z9uLnRL.png",
	},
	{
		name: "Kraft & Dele Αυτόματος Απογυμνωτής Καλωδίων",
		description: "Ο απογυμνωτής καλωδίων, από την εταιρία Kraft&Dele, είναι κατάλληλος για την αφαίρεση μόνωσης από μονόπλευρα και πολυπύρηνα καλώδια (επιπλέον μονωμένα). Έχει σκληρυμένες λεπίδες, αντιολισθητική λαβή από καουτσούκ και προσαρμόζεται αυτόματα στη διατομή του επεξεργασμένου αγωγού κατά τη διαδικασία απογύμνωσης.",
		category: "Απογυμνωτής Καλωδίων",
		amount: "",
		image: "https://i.imgur.com/Q3n3RpL.png",
	},
	{
		name: "Inter Ψαλίδι Κλαδέματος Μήκους 23cm",
		description: "Kλαδευτήρι INTER εξαιρετικής ποιότητας. Λεπίδα επιχρωμιωμένη εξαιρετικής κοπτικής αιχμής. Με ανατομικές λαβές. Με ελατήριο. Η συσκευασία περιλαμβάνει και μια ανταλλακτική λεπίδα και ελατήριο.",
		category: "Ψαλίδι",
		amount: "",
		image: "https://i.imgur.com/LdAkvtb.png",
	},
	{
		name: "Ankor Ψαλίδι Τρύγου Μήκους 20cm",
		description: "Κλαδευτήρι χειρός 20εκ. μεγάλης αντοχής, για γενικές εργασίες κλαδέματος, ειδικά σχεδιασμένο για λαχανόκηπους, καλλιεργητές και κηπουρούς. Διαθέτει: Εργονομική λαβή για άνετο και ξεκούραστο πιάσιμο, δυνατό και εύκαμπτο ελατήριο και μηχανισμό κλειδώματος στα άκρα.",
		category: "Ψαλίδι",
		amount: "",
		image: "https://i.imgur.com/WdOegf9.png",
	},
	{
		name: "SIT Συρματόβουρτσα Χειρός με Πλαστική Λαβή",
		description: "Συρματόβουρτσα για την αφαίρεση σκουριάς, χρωμάτων και βρωμιών από επιφάνειες. Διαθέτει σύρμα από χάλυβα 0.30mm και έχει συνολικό μήκος 245mm.",
		category: "Συρματόβουρτσα",
		amount: "",
		image: "https://i.imgur.com/vlivOZM.png",
	},
	{
		name: "Mentor Set Σπάτουλα \& Ξύστρα Σιλικόνης",
		description: "",
		category: "Ξύστρα Σιλικόνης",
		amount: "",
		image: "https://i.imgur.com/8GEuAOK.png",
	},
	{
		name: "Varta Αλκαλική Mπαταρία 23A 12V",
		description: "",
		category: "Μπαταρία",
		amount: "",
		image: "https://s6.imgcdn.dev/JTICg.webp",
	},
	{
		name: "Toshiba High Power Μπαταρίες - ΑΑΑ",
		description: "Toshiba AAA High Power Αλκαλικές Μπαταρίες. Η τεχνολογία που ενσωματώνεται στις μπαταρίες Toshiba AAA έχει σχεδιαστεί για να διαρκούν και να διαρκούν και να διαρκούν. Αποτελούν αξιόπιστες πηγές ενέργειας. Είναι συμβατές με όλες τις ψηφιακές συσκευές που δέχονται μπαταρίες τύπου AAA.",
		category: "Μπαταρία",
		amount: "",
		image: "https://s6.imgcdn.dev/JTN7v.webp",
	},
	{
		name: "Μπαταρία Varta Longlife Extra AAA",
		description: "Αλκαλικές μπαταρίες Varta LongLife Extra, 1,5 Volt μέγεθος AAA, συσκευασία 4 τεμαχίων.Κατάλληλες για χρήση σε τηλεχειριστήρια τηλεοράσεων & Hi-Fi, φακούς και ρολόγια.",
		category: "Μπαταρία",
		amount: "",
		image: "https://s6.imgcdn.dev/JTQLN.webp",
	},
	{
		name: "Vorel Πιστόλι Σιλικόνης",
		description: "Ελαφρύ πιστόλι σιλικόνης από σίδηρο που ταιριάζει στα τυπικά φυσίγγια 300 ml μήκους 230 mm με σιλικόνη ή κόλλα. Για τη συμπίεση πυκνών μαζών / κόλλας / σιλικόνων / στεγανωτικών, που χρησιμοποιούνται για εργασίες ανακαίνισης και φινιρίσματος. Χωρητικότητα σωλήνα 300 ml.",
		category: "Πιστόλι Σιλικόνης",
		amount: "",
		image: "https://s6.imgcdn.dev/JTkwq.webp",
	},
	{
		name: "Tajima Πιστόλι Σιλικόνης",
		description: "Διαθέτει σύστημα διανομής διπλής ώθησης και αυτόματη διακοπή ροής, δίνοντάς το πλεονέκτημα της αναλογίας 12:1.",
		category: "Πιστόλι Σιλικόνης",
		amount: "",
		image: "https://s6.imgcdn.dev/JTnUB.webp",
	},
	{
		name: "OnSite Σετ Κατσαβίδια Ακριβείας",
		description: "OnSite Κατσαβίδια ακριβείας ωρολογοποιών",
		category: "Κατσαβίδι",
		amount: "",
		image: "https://s6.imgcdn.dev/JTsVu.webp",
	},
	{
		name: "Varta Μπαταρία Λιθίου 3V",
		description: "Η premium μπαταρία Varta έχει σχεδιαστεί για να παρέχει αξιόπιστη ισχύ για μικρές ηλεκτρονικές συσκευές. Οι μπαταρίες προσφέρουν την υψηλότερη απόδοση για εφαρμογές παλμικής και συνεχούς εκφόρτισης. Όλα τα κουμπιά λιθίου Varta είναι συσκευασμένα για παιδιά και πληρούν τα υψηλότερα πρότυπα ασφαλείας. Εγγυημένη η καλύτερη ποιότητα και διάρκεια.",
		category: "Μπαταρία",
		amount: "",
		image: "https://s6.imgcdn.dev/JTyoL.webp",
	},
	{
		name: "Varta LongLife Power Αλκαλικές Μπαταρίες",
		description: "",
		category: "Μπαταρία",
		amount: "",
		image: "https://s6.imgcdn.dev/JTKsa.webp",
	},
	{
		name: "TOSHIBA SUPER Αλκαλική Μπαταρία 9V",
		description: "",
		category: "Μπαταρία",
		amount: "",
		image: "https://s6.imgcdn.dev/JTP2w.webp",
	},
	{
		name: "Toshiba Αλκαλικές Μπαταρίες Ρολογιών 1.5V 10τμχ",
		description: "Σετ 10 μπαταριών για μικρές συσκευές όπως κομπιουτεράκια, ρολόγια, κλειδιά αυτοκινήτων και άλλα.",
		category: "Μπαταρία",
		amount: "",
		image: "https://s6.imgcdn.dev/JTTHt.webp",
	},
	{
		name: "Sola PTM5 Πλαστικό Αλφάδι",
		description: "Αλφάδι μίνι μαγνητικό κατασκευασμένο από συμπαγές πλαστικό ABS. Περιέχει φιαλίδια ακρυλικού σωλήνα που είναι ανθεκτικά στη θραύση. Το αλφάδι έχει μαγνητική λωρίδα για δυνατό κράτημα σε μεταλλικές επιφάνειες. Είναι ανθεκτικό στο νερό, στην θερμότητα και στο κρύο. Μπορεί να εφαρμοστεί σε οριζόντια, κάθετη ακόμα και σε γωνία με κλίση 45°.",
		category: "Αλφάδι",
		amount: "",
		image: "https://s6.imgcdn.dev/JSAZv.webp",
	},
	{
		name: "Πένσα Διάτρησης Προφίλ Γυψοσανίδας",
		description: "",
		category: "Πένσα",
		amount: "",
		image: "https://s6.imgcdn.dev/JSpjC.webp",
	},
	{
		name: "Δίσκος Λείανσης Smirdex",
		description: "Στρογγυλό Χωρίς Τρύπες Velcro 115mm & 125mm",
		category: "Δίσκος Λείανσης",
		amount: "",
		image: "https://s6.imgcdn.dev/JrhJM.webp",
	},
	{
		name: "Μπουντούζια Αλουμινίου Σέτ 100 Τεμ",
		description: "Μπουντούζια Αλουμινίου (Σέτ 100 Τεμ) TECHBOSS. Ιδανική επιλογή για λινάτσες, μουσαμάδες και τεντόπανα.",
		category: "Μπουντούζια",
		amount: "",
		image: "https://s6.imgcdn.dev/Jxe9n.webp",
	},
	{
		name: "Αυτορυθμιζόμενο Γραμμικό Αλφάδι Laser",
		description: "Παγώνει & σπάει τη σκουριά ενώ ταυτόχρονα λιπαίνει, κατευθυνόμενος ψεκασμός, με εξαιρετικές λιπαντικές ιδιότητες.",
		category: "Αλφάδι",
		amount: "",
		image: "https://s6.imgcdn.dev/pkO9S.webp",
	},
	{
		name: "Ψηφιακός Ανιχνευτής Καλωδίων, Μετάλλου & Ξύλου",
		description: "Διάσταση οθόνης: 2,2'', Βάθος ανίχνευσης: Μαγνητικά Μέταλλα 8 cm / Μη Μαγνητικά Μέταλλα 5 cm / Καλώδια AC 5 cm / Ξύλο 2 cm, Βαθμός προστασίας: IP54, Μονάδα μέτρησης: cm / in, Τύπος μπαταρίας: 3xΑΑΑ",
		category: "Ανιχνευτής",
		amount: "",
		image: "https://s6.imgcdn.dev/pkZJC.webp",
	},
	/* Ούπατ */
	{
		name: "Πλαστικά Βίσματα",
		description: "Διαθέσιμα σε No6, No7, No8, No10.",
		category: "Ούπατ",
		amount: "",
		image: "https://s6.imgcdn.dev/YDWAhg.webp",
	},
	{
		name: "Βίσματα G\&B",
		description: "Καλής ποιότητας βίσματα.",
		category: "Ούπατ",
		amount: "",
		image: "https://s6.imgcdn.dev/YDWOPv.webp",
	},
	{
		name: "Βίσματα Smart",
		description: "Καλής ποιότητας βίσματα.",
		category: "Ούπατ",
		amount: "",
		image: "https://s6.imgcdn.dev/YDWVkB.webp",
	},
	{
		name: "Fischer Βίσματα",
		description: "Άριστης ποιότητας βίσματα, με πολύ καλή εκτόνωση.",
		category: "Ούπατ",
		amount: "",
		image: "https://s6.imgcdn.dev/YDW98q.webp",
	},
	/* Τέλος ούπατ */
	{
		name: "Ρόκα Στηρίγματα Καλωδίων",
		description: "Διαθέσιμα σε πολλά διαφορετικά μεγέθη.",
		category: "Ρόκα",
		amount: "",
		image: "https://s6.imgcdn.dev/YDWZ9N.webp",
	},
	{
		name: "Νάιλον 4x5 Ψιλό",
		description: "",
		category: "Νάιλον",
		amount: "",
		image: "https://s6.imgcdn.dev/YDWfvu.webp",
	},
	{
		name: "Νάιλον 4x5 Μεσαίο",
		description: "",
		category: "Νάιλον",
		amount: "",
		image: "https://s6.imgcdn.dev/YDWtqL.webp",
	},
	{
		name: "Νάιλον 4x5 Χονδρό",
		description: "",
		category: "Νάιλον",
		amount: "",
		image: "https://s6.imgcdn.dev/YDWd4a.webp",
	},
	{
		name: "Υαλόχαρτο σε Φύλλα",
		description: "",
		category: "Υαλόχαρτο",
		amount: "",
		image: "https://s6.imgcdn.dev/YDW30w.webp",
	},
	{
		name: "Benman 1/4\" Μαγνητικός adaptor για στριφώνια",
		description: "Διαθέσιμος για 8 mm, 10 mm και 13 mm.",
		category: "Μαγνητικός adaptor",
		amount: "",
		image: "https://s6.imgcdn.dev/YDWLdt.webp",
	},
	{
		name: "Μάσκα Κυπελλοειδής σωματιδίων άνθρακα",
		description: "Προσφέρει προστασία από χρώματα και χρωστικές ουσίες – Σκληρή συγκόλληση και εργασία με λιωμένα μέταλλα – Σιδηρούχες και μη μεταλλουργικές βιομηχανίες- Λιπάσματα.",
		category: "Μάσκα",
		amount: "",
		image: "https://s6.imgcdn.dev/YYcoB2.webp",
	},
]